default_language_version:
  python: python3.9

repos:
  - repo: https://github.com/hadolint/hadolint
    rev: "v2.10.0"
    hooks:
      - id: hadolint-docker

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args:
          - --safe
          - --quiet
          - --line-length=88

  - repo: https://github.com/PyCQA/isort
    rev: "5.10.1"
    hooks:
      - id: isort
        args: ["--profile", "black"]
        additional_dependencies: [toml]
        exclude: docs/tutorials

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==22.1.0]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
        exclude: _pytest/(debugging|hookspec).py
        language_version: python3

  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        name: autoflake
        args:
          - --in-place
          - --remove-unused-variables
          - --remove-all-unused-imports
        language: python
        files: \.py$

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-typing-imports==1.12.0
          - flake8-docstrings==1.5.0
        args:
          # making isort line length compatible with black
          - --select=B,C,E,F,W,T4,B9
          - --max-line-length=88
          - --max-complexity=18
          - --ignore=D100,D102,D103,D104
        # https://flake8.pycqa.org/en/latest/user/error-codes.html

  - repo: https://github.com/rtts/djhtml
    rev: "v1.5.0"
    hooks:
      - id: djhtml
      - id: djcss
      - id: djjs

  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.7.0
    hooks:
      - id: django-upgrade
        args: [--target-version, "4.0"]

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.34.0
    hooks:
      - id: pyupgrade
        args: [--py39-plus]

  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.20.1
    hooks:
      - id: setup-cfg-fmt
        args: [--max-py-version=3.10]

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-use-type-annotations

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy
        additional_dependencies: [types-all]

  # prettier - formatting JS, CSS, JSON, Markdown, ...
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier

  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.6
    hooks:
      - id: python-bandit-vulnerability-check
        args: [-lll, src]
        files: .py$
